services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: registry.floxsite.de/kindle-dashboard:latest
    # environment:
    #   - POLARS_SKIP_CPU_CHECK=1
    env_file:
      - .env
